### ISSUE TITLE
Verify that IncludedConfigurations system property works

### ISSUE THREAD

**Issue by akamen** [blackducksoftware/hub-gradle-plugin#18]
@drewtwitchell  based on your call with a customer asking to expand scopes, can you verify the following:

IncludedConfigurations can be set as system property. 
They can then list the scopes they are interested in, comma separated.

**Comment by drewtwitchell** [comment]
@akamen I have just included you on an email with that company that asked about this. Please advise.

**Comment by psantos1113** [comment]
I have tested the IncludedConfigurations property.  Use a java -D option to set it on the command line.
In order to include the -D java option on the command line it looks like you need to use the gradle wrapper to execute the build.  Execute gradle wrapper to generate the gradle wrapper.  Then you can invoke the ./gradlew with the java property set.  An example is shown below.  
example:  ./gradlew deployHubOutputAndCheckPolicies -DIncludedConfigurations="testCompile,runtime"

**Comment by psantos1113** [comment]
includedConfigurations will be a configurable property in the gradle tasks in the 3.2.0 version.  About to commit the changes to include it.
