### ISSUE TITLE
Consistent non-failing timeouts

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/hub-gradle-plugin#22]
When using "deployHubOutput" I'm consistently getting:
`[09:49:53]	[Step 1/1] 09:49:53.033 [ERROR] [com.blackducksoftware.integration.gradle.PluginHelper] There was an error waiting for the scans: No scan has started within the specified wait time: 5 minutes`

There are 2 problems here:
1) The gradle error doesn't actually stop the build. Gradle just continues and eventually says success.
2) Despite this error and the timeout, the BOM *does* successfully get uploaded to blackduck.

How can I determine what is causing these timeouts?
Is there any way to tell the plugin not to wait for the scan as if the upload works then everything should be fine correct?

My configuration:
` deployHubOutput {
        if (project.hasProperty("bd_proj_name")) {
            hubProjectName project.properties.bd_proj_name;
        } else {
            throw new Exception("You must specify a bd_proj_name property");
        }
        if (project.hasProperty("bd_proj_version")) {
            hubVersionName project.properties.bd_proj_version;
        } else {
            throw new Exception("You must specify a bd_proj_version property");
        }
        hubUrl = "[Redacted]"
        hubUsername = "[Redacted]"
        hubPassword = "[Redacted]"
}`

**Comment by imbeyondboredom** [comment]
I can't seem to get the gradle config correctly formatted on here. Sorry it's hard to read.

**Comment by ekerwin** [comment]
This "error" is most likely caused from the hub server not completing the import of bdio before the specified timeout. That "scan started" timeout is usually due to too many pending scans.

As for why it doesn't fail your build, it is not a true error case as we define it because, as you noticed, the bom DOES get created eventually.

When we complete the current feature to allow for configuring the plugin to only deploy the output and not wait for a policy check, I will update and close this issue - we are working on it now for our next release in the coming weeks.
