### ISSUE TITLE
BlackDuck Hub 3.5.1 Groups scans regardless of version

### ISSUE THREAD

**Issue by imbeyondboredom** [blackducksoftware/hub-gradle-plugin#25]
From my initial investigation it looks like the "spdx:name" overrides the "name" and "Revision" parameters. 

I can't upload the file at this time (Assuming github uses S3 servers for that) but basically I have the following scan paths:

Host: "mvn:/home/buildagent/buildAgent/work/f0968067a417eae9/f0968067a417eae9/In_Development"
Path:
"<Project Name> Black Duck I/O Export"

AND

Host: "mvn:/home/buildagent/buildAgent/work/4ef9e7176026c4a3/4ef9e7176026c4a3/Pre_Release"
Path:
"<Project Name> Black Duck I/O Export"

Both of these map to the same project and actually override which version it points to based on whatever is run last...

**Comment by imbeyondboredom** [comment]
Note that my maven group probably looks odd because of #23... but the 3.5.1 version of black duck hub appears to ignore that field when mapping to projects which is my problem.

**Comment by imbeyondboredom** [comment]
Adding the image that proves that this has nothing to do with the strange artifact path I have:

<img width="944" alt="screen shot 2017-03-16 at 2 39 25 pm" src="https://cloud.githubusercontent.com/assets/86616/24013012/706f4604-0a56-11e7-8f5b-61e0fd691fc4.png">

**Comment by imbeyondboredom** [comment]
`[ {
  "@id" : "uuid:9d4748be-6d57-4d13-9d00-a6c7cc6599f1",
  "@type" : "BillOfMaterials",
  "specVersion" : "1.1.0",
  "spdx:name" : "DeviceVault - TEST Black Duck I/O Export",
  "creationInfo" : {
    "spdx:creator" : "Tool: Gradle-2.2.1",
    "spdx:created" : "2017-03-16T18:31:55.000Z"
  }
}, {
  "@id" : "mvn:com.a/Project1/1.1",
  "@type" : "Project",
  "name" : "DeviceVault - TEST",
  "revision" : "1.1",
  "externalIdentifier" : {
    "externalSystemTypeId" : "maven",
    "externalId" : "com.a:Project1:1.1"
  },
`

AND

`[ {
  "@id" : "uuid:185a5149-9bca-48e9-8afb-21a6f9c0bbbe",
  "@type" : "BillOfMaterials",
  "specVersion" : "1.1.0",
  "spdx:name" : "DeviceVault - TEST Black Duck I/O Export",
  "creationInfo" : {
    "spdx:creator" : "Tool: Gradle-2.2.1",
    "spdx:created" : "2017-03-16T18:36:00.000Z"
  }
}, {
  "@id" : "mvn:com.b/Project2/1.2",
  "@type" : "Project",
  "name" : "DeviceVault - TEST",
  "revision" : "1.2",
  "externalIdentifier" : {
    "externalSystemTypeId" : "maven",
    "externalId" : "com.b:Project2:1.2"
  },
`

**Comment by imbeyondboredom** [comment]
@psantos1113 Is there anything else you need from me? As illustrated this issue has nothing to do with #23 and it basically makes the gradle plugin unusable unless you only ever scan one version of your code.

@akamen Are you the right person instead to ping on this?

**Comment by psantos1113** [comment]
Hi @imbeyondboredom there isn't anything else we need from you on this.  The issue here is that both “Project1” and “Project2” have the same project name in the BDIO generated for each project.  Therefore both code locations get mapped to the same project.  In the BDIO output you've attached the project name for both projects is "name" : "DeviceVault - TEST".  That is the source of the problem.  Both code locations are mapped to the same project, but only one is uploaded at a time.  The last uploaded file takes precedence when importing BDIO.  That is how the import of BDIO works in the Hub.  That is why you are having the issue you are seeing.

I believe you have the tools you need to solve the problem.  From what I understand you are using a script to configure our hub-gradle plugin.  In your script make sure the hubProjectName
field is configured to a unique project name for each project.  The plugin should be run for each individual project. This is where you can get the same effect of the change from your pull request.  

hubProjectName = “${projectDir}:${project.name}:${project.version}”  (that will achieve the same functionality of your pull request)

If you’re using a build script similar to that linked in issue #23, then make sure the project.properties.bd_proj_name isn’t returning the same value for each project. 

If the issue is that both code locations should be associated with the same project, so that you have a BOM that contains data from Project1 and Project2, then currently that isn't supported.   The notion of sub-projects or modules is what you are looking for.  You’d be looking for project “DeviceVault – TEST” contains sub-projects “Project1” and “Project2” and the BOM for “DeviceVault – TEST” is the aggregation of the BOMs of “Project1” and “Project2.”   Currently that isn’t supported.  If you need that functionality please open an enhancement ticket for the plugin.

**Comment by imbeyondboredom** [comment]
@psantos1113 Thanks for the clarifications but you're still missing my point. The issue that I'm having is that they should be separate. In this case every project will lose all version information except for whatever was last scanned.

The only reason I changed the package name and version information is to illustrate that everything is being grouped by the blackduck hub based on the project name and that, if that is the case, the project name HAS to include the version of the app so that you can have more than one version of the app in the black duck hub.

**Comment by ekerwin** [comment]
@imbeyondboredom - we think this is how your projects might be setup: https://github.com/blackducksoftware/gradle-sample/tree/no_settings_with_overrides

With that config, the bdio is created and uploads fine. Can you please give us a PR to change this config or project structure to more closely resemble what you are doing? We're getting close to a release of this plugin and we don't want to miss a chance to fix your issue while we're at it. Thanks!

**Comment by imbeyondboredom** [comment]
@ekerwin Ah perfect. So I could submit a pull request but a better way to illustrate what I'm saying is to do the following: 
1)Deploy the hub output of ProjectA
2)Change the version number of ProjectA (In my case I change it to `    hubVersionName = "a_override_version_2"`
3)Re-deploy ProjectA

You should get the following where the second version overrides the first:
<img width="1186" alt="screen shot 2017-03-22 at 2 43 53 pm" src="https://cloud.githubusercontent.com/assets/86616/24215189/56b72c88-0f0e-11e7-8e26-4b06cc2bffd3.png">

**Comment by ekerwin** [comment]
@imbeyondboredom I tried to follow those steps. I deployed Project A's output, which resulted in a single code location being created in the hub which was automatically mapped to a new hub project 'a_override_name' and version 'a_override_version'. This is the bdio file that was created:
[ProjectA_bdio.jsonld.txt](https://github.com/blackducksoftware/hub-gradle-plugin/files/862726/ProjectA_bdio.jsonld.txt)

Then, I changed the hubProjectVersion to 'a_override_version_2' and deployed the resulting output. It created a new code location, which was mapped to a new version of the 'a_override_name' project. Here is the resulting bdio:
[ProjectA_bdio.jsonld.txt](https://github.com/blackducksoftware/hub-gradle-plugin/files/862728/ProjectA_bdio.jsonld.txt)

This is the behavior we'd expect. Did I not understand your steps?

If you upload those bdio files manually, do you not get this output?
<img width="1308" alt="screen shot 2017-03-22 at 4 06 40 pm" src="https://cloud.githubusercontent.com/assets/224544/24218526/fb289abc-0f19-11e7-88ef-ff04b7763fb3.png">

**Comment by ekerwin** [comment]
Also, please note that each subsequent upload of bdio for project X/version Y WILL override the previously created BOM, but this is by design. So if you have developers producing and uploading bdio from their machines for the same project/version (this would definitely be the case for a project under active development by more than one team member), the latest (most current) one wins. Is this the issue we're dealing with here?

**Comment by imbeyondboredom** [comment]
We only get one code location with two entries underneath it. I used to get the behavior you described until we updated to Hub v3.5.2

**Comment by imbeyondboredom** [comment]
Here's the only code location that we see on our installation:
<img width="1399" alt="screen shot 2017-03-22 at 4 27 41 pm" src="https://cloud.githubusercontent.com/assets/86616/24219253/88b8420e-0f1c-11e7-8303-99ac2c94914c.png">

**Comment by ekerwin** [comment]
okay, checking against Hub 3.5.2 now

**Comment by ekerwin** [comment]
Awesome - I can reproduce this now! It looks like either we are not producing the bdio correctly for Hub 3.5.2+ or Hub 3.5.2+ is not supporting bdio the way they should. When I upload those two bdio files for Hub 3.5.2, I get the terrible overriding behavior you experience. Huzzah!

**Comment by imbeyondboredom** [comment]
YAY! haha lesson learned that I should create a simple repo instead of the more complex example where I tried to show that two separate projects were getting grouped. That led to too much confusion.

**Comment by psantos1113** [comment]
@imbeyondboredom I apologize for the confusion with this issue.  It took us a few iterations to get there today but we got there.  Thank you for your patience!

**Comment by akamen** [comment]
@imbeyondboredom thanks for the patience!  We will see communicate the status of this (not yet confirmed) bug through your CSM!

**Comment by akamen** [comment]
@imbeyondboredom 4.0.0 released.  Please try it and let us know if this issue and others are addressed

**Comment by imbeyondboredom** [comment]
Following up on this - this is fixed with the latest plugin and hub. This issue is already closed but just wanted to close the loop here.

**Comment by akamen** [comment]
Thanks!
